export const guestList = [
  {
    name1: "ZERO INDEX PLACEHOLDER",
    name2: "ZERO INDEX PLACEHOLDER",
    totalGuests: 0,
    index: 0,
  },
  {
    name1: "Aaron Fichtelberg",
    name2: "Renee Bowers",
    totalGuests: 4,
    index: 1,
  },
  {
    name1: "Abigail Higdon",
    name2: "Abigail Higdon",
    totalGuests: 1,
    index: 2,
  },
  {
    name1: "Adam Potts",
    name2: "Katie Potts",
    totalGuests: 2,
    index: 3,
  },
  {
    name1: "Alex Turley",
    name2: "Alex Turley",
    totalGuests: 1,
    index: 4,
  },
  {
    name1: "Alexander Burgess",
    name2: "Joni Burgess",
    totalGuests: 2,
    index: 5,
  },
  {
    name1: "Alexander Williams",
    name2: "Alexander Williams",
    totalGuests: 1,
    index: 6,
  },
  {
    name1: "Andrew Israel",
    name2: "Andrew Israel",
    totalGuests: 2,
    index: 7,
  },
  {
    name1: "Andy Spera",
    name2: "Diana Spera",
    totalGuests: 2,
    index: 8,
  },
  {
    name1: "Annie Pettit",
    name2: "Annie Pettit",
    totalGuests: 1,
    index: 9,
  },
  {
    name1: "Ariana Lonske",
    name2: "Matthew",
    totalGuests: 2,
    index: 10,
  },
  {
    name1: "Austin Hanke",
    name2: "Austin Hanke",
    totalGuests: 1,
    index: 11,
  },
  {
    name1: "Benjamin Bowers",
    name2: "Denee Bowers",
    totalGuests: 3,
    index: 12,
  },
  {
    name1: "Benjamin Sota",
    name2: "Michelle Sota",
    totalGuests: 2,
    index: 13,
  },
  {
    name1: "Brendan Wren",
    name2: "Brendan Wren",
    totalGuests: 2,
    index: 14,
  },
  {
    name1: "Brooke Koester",
    name2: "Brooke Koester",
    totalGuests: 1,
    index: 15,
  },
  {
    name1: "Caitlyn Warren",
    name2: "Caitlyn Warren",
    totalGuests: 2,
    index: 16,
  },
  {
    name1: "Cameron Brantley",
    name2: "Cameron Brantley",
    totalGuests: 1,
    index: 17,
  },
  {
    name1: "Cary Israel",
    name2: "Michelle Israel",
    totalGuests: 2,
    index: 18,
  },
  {
    name1: "Chad Olney",
    name2: "Tessa Olney",
    totalGuests: 3,
    index: 19,
  },
  {
    name1: "Charles Kuhn",
    name2: "Becky Kuhn",
    totalGuests: 2,
    index: 20,
  },
  {
    name1: "Christian Veluz",
    name2: "Jaime Veluz",
    totalGuests: 2,
    index: 21,
  },
  {
    name1: "Christopher Alsruhe",
    name2: "Sandy Alsruhe",
    totalGuests: 2,
    index: 22,
  },
  {
    name1: "Christy Jorgensen",
    name2: "Christy Jorgensen",
    totalGuests: 1,
    index: 23,
  },
  {
    name1: "Corey McNab",
    name2: "Corey McNab",
    totalGuests: 1,
    index: 24,
  },
  {
    name1: "Danielle Bowers",
    name2: "Danielle Bowers",
    totalGuests: 2,
    index: 25,
  },
  {
    name1: "David Israel",
    name2: "David Israel",
    totalGuests: 2,
    index: 26,
  },
  {
    name1: "David Jorgensen",
    name2: "David Jorgensen",
    totalGuests: 1,
    index: 27,
  },
  {
    name1: "David Reiher",
    name2: "Arlene Reiher",
    totalGuests: 2,
    index: 28,
  },
  {
    name1: "Dorian Thorne",
    name2: "Dorian Thorne",
    totalGuests: 1,
    index: 29,
  },
  {
    name1: "Dylan J",
    name2: "Dylan J",
    totalGuests: 1,
    index: 30,
  },
  {
    name1: "Ella Kelly",
    name2: "Ella Kelly",
    totalGuests: 1,
    index: 31,
  },
  {
    name1: "Emily Foster",
    name2: "Emily Foster",
    totalGuests: 2,
    index: 32,
  },
  {
    name1: "Emily Rauch",
    name2: "Emily Rauch",
    totalGuests: 1,
    index: 33,
  },
  {
    name1: "Erica Campbell",
    name2: "Erica Campbell",
    totalGuests: 1,
    index: 34,
  },
  {
    name1: "Erin Kiely",
    name2: "Erin Kiely",
    totalGuests: 2,
    index: 35,
  },
  {
    name1: "Glenn Herr",
    name2: "Narci Herr",
    totalGuests: 2,
    index: 36,
  },
  {
    name1: "Gretchen Fowler",
    name2: "Gretchen Fowler",
    totalGuests: 2,
    index: 37,
  },
  {
    name1: "Herson Lopez",
    name2: "Gloria Lopez",
    totalGuests: 2,
    index: 38,
  },
  {
    name1: "Howard Appelman",
    name2: "Pam Appelman",
    totalGuests: 2,
    index: 39,
  },
  {
    name1: "Howard Schlesinger",
    name2: "Laurie Schlesinger",
    totalGuests: 4,
    index: 40,
  },
  {
    name1: "Jack Steinberg",
    name2: "Jack Steinberg",
    totalGuests: 1,
    index: 41,
  },
  {
    name1: "James Bowers",
    name2: "Jennifer Bowers",
    totalGuests: 2,
    index: 42,
  },
  {
    name1: "James Israel",
    name2: "Vicki Israel",
    totalGuests: 2,
    index: 43,
  },
  {
    name1: "Jamie Israel",
    name2: "Jamie Israel",
    totalGuests: 1,
    index: 44,
  },
  {
    name1: "Jeffrey Lawrence",
    name2: "Donna Lawrence",
    totalGuests: 2,
    index: 45,
  },
  {
    name1: "Joe Ruzicka",
    name2: "Joe Ruzicka",
    totalGuests: 1,
    index: 46,
  },
  {
    name1: "Joel Alsruhe",
    name2: "Holly Alsruhe",
    totalGuests: 2,
    index: 47,
  },
  {
    name1: "John Hamm",
    name2: "Susan Barry",
    totalGuests: 2,
    index: 48,
  },
  {
    name1: "John Kohn",
    name2: "Sati Kohn",
    totalGuests: 2,
    index: 49,
  },
  {
    name1: "John Reinert",
    name2: "John Reinert",
    totalGuests: 2,
    index: 50,
  },
  {
    name1: "John Van't Land",
    name2: "Jenny Van't Land",
    totalGuests: 4,
    index: 51,
  },
  {
    name1: "Joseph Bowers",
    name2: "Linda Bowers",
    totalGuests: 2,
    index: 52,
  },
  {
    name1: "Joseph Lee",
    name2: "Joseph Lee",
    totalGuests: 1,
    index: 53,
  },
  {
    name1: "Justin Krackmalnick",
    name2: "Justin Krackmalnick",
    totalGuests: 2,
    index: 54,
  },
  {
    name1: "Keith Sutherland",
    name2: "Keith Sutherland",
    totalGuests: 2,
    index: 55,
  },
  {
    name1: "Kenneth Israel",
    name2: "Kenneth Israel",
    totalGuests: 4,
    index: 56,
  },
  {
    name1: "Kevin Xu",
    name2: "Anabeth Liu",
    totalGuests: 2,
    index: 57,
  },
  {
    name1: "Kurtis Duemler",
    name2: "Leanna Duemler",
    totalGuests: 2,
    index: 58,
  },
  {
    name1: "Larry Miller",
    name2: "Jeanie Miller",
    totalGuests: 2,
    index: 59,
  },
  {
    name1: "Lauren Bellamy",
    name2: "Lauren Bellamy",
    totalGuests: 1,
    index: 60,
  },
  {
    name1: "Lindsay Appelman",
    name2: "Lindsay Appelman",
    totalGuests: 1,
    index: 61,
  },
  {
    name1: "Louis Bowers",
    name2: "Joyce Bowers",
    totalGuests: 2,
    index: 62,
  },
  {
    name1: "Lowell Steinberg",
    name2: "Ilyse Steinberg",
    totalGuests: 2,
    index: 63,
  },
  {
    name1: "Madelyn Cook",
    name2: "husband?",
    totalGuests: 2,
    index: 64,
  },
  {
    name1: "Mark Harris",
    name2: "Marcie Harris",
    totalGuests: 4,
    index: 65,
  },
  {
    name1: "Martin Leathers",
    name2: "Hannah Leathers",
    totalGuests: 3,
    index: 66,
  },
  {
    name1: "Matt Erbes",
    name2: "Nikki Erbes",
    totalGuests: 3,
    index: 67,
  },
  {
    name1: "Matt Gombos",
    name2: "Sarah Gombos",
    totalGuests: 2,
    index: 68,
  },
  {
    name1: "Matthew Shenouda",
    name2: "Matthew Shenouda",
    totalGuests: 1,
    index: 69,
  },
  {
    name1: "Melanie Ernst",
    name2: "Melanie Ernst",
    totalGuests: 2,
    index: 70,
  },
  {
    name1: "Michael Barrett",
    name2: "Ashley Howe",
    totalGuests: 2,
    index: 71,
  },
  {
    name1: "Micheal Weaver",
    name2: "Sue Weaver",
    totalGuests: 2,
    index: 72,
  },
  {
    name1: "Molly Brinkmann",
    name2: "Molly Brinkmann",
    totalGuests: 1,
    index: 73,
  },
  {
    name1: "Monroe Givens",
    name2: "Judy Givens",
    totalGuests: 2,
    index: 74,
  },
  {
    name1: "Moses Morrison",
    name2: "Roseanne Morrison",
    totalGuests: 4,
    index: 75,
  },
  {
    name1: "Nathan Israel",
    name2: "Nathan Israel",
    totalGuests: 1,
    index: 76,
  },
  {
    name1: "Nicholas Chiu",
    name2: "Nicholas Chiu",
    totalGuests: 1,
    index: 77,
  },
  {
    name1: "Nick Backstrom",
    name2: "Claire Backstrom",
    totalGuests: 2,
    index: 78,
  },
  {
    name1: "Patricia Howe",
    name2: "Patricia Howe",
    totalGuests: 2,
    index: 79,
  },
  {
    name1: "Patrick Christie",
    name2: "Connilee Christie",
    totalGuests: 4,
    index: 80,
  },
  {
    name1: "Patrick Daniere",
    name2: "Rose-Marie Daniere",
    totalGuests: 2,
    index: 81,
  },
  {
    name1: "Paul Bowers",
    name2: "Evie Bowers",
    totalGuests: 2,
    index: 82,
  },
  {
    name1: "Paul Sinclair",
    name2: "Lisa Sinclair",
    totalGuests: 2,
    index: 83,
  },
  {
    name1: "Peter Jorgensen",
    name2: "Sandy Jorgensen",
    totalGuests: 2,
    index: 84,
  },
  {
    name1: "Raneda Smith",
    name2: "Raneda Smith",
    totalGuests: 1,
    index: 85,
  },
  {
    name1: "Rebecca Waines",
    name2: "Rebecca Waines",
    totalGuests: 1,
    index: 86,
  },
  {
    name1: "Robert Bowers",
    name2: "Marian Bowers",
    totalGuests: 2,
    index: 87,
  },
  {
    name1: "Robert Holden",
    name2: "Abby Holden",
    totalGuests: 2,
    index: 88,
  },
  {
    name1: "Ronald Menghini",
    name2: "Ronald Menghini",
    totalGuests: 1,
    index: 89,
  },
  {
    name1: "Ruthanne Bowers",
    name2: "Ruthanne Bowers",
    totalGuests: 2,
    index: 90,
  },
  {
    name1: "Sadie Moore",
    name2: "Sadie Moore",
    totalGuests: 1,
    index: 91,
  },
  {
    name1: "Sanford Krachmalnick",
    name2: "Sandra Krachmalnick",
    totalGuests: 2,
    index: 92,
  },
  {
    name1: "Sara Krachmalnick",
    name2: "Matt Cook",
    totalGuests: 2,
    index: 93,
  },
  {
    name1: "Scott Humpherys",
    name2: "Emily Humpherys",
    totalGuests: 4,
    index: 94,
  },
  {
    name1: "Scott Needham",
    name2: "Marilyn Needham",
    totalGuests: 2,
    index: 95,
  },
  {
    name1: "Steffan Davidson",
    name2: "Hannah Davidson",
    totalGuests: 2,
    index: 96,
  },
  {
    name1: "Stephanie Gaide",
    name2: "Stephanie Gaide",
    totalGuests: 1,
    index: 97,
  },
  {
    name1: "Stephanie Wegner",
    name2: "Stephanie Wegner",
    totalGuests: 1,
    index: 98,
  },
  {
    name1: "Stephen Groves",
    name2: "Kelsey Groves",
    totalGuests: 5,
    index: 99,
  },
  {
    name1: "Steven Bien-Aime",
    name2: "Alyssa Appelman",
    totalGuests: 2,
    index: 100,
  },
  {
    name1: "Steven Israel",
    name2: "Steven Israel",
    totalGuests: 2,
    index: 101,
  },
  {
    name1: "Thomas Hudzina",
    name2: "Ruth Hudzina",
    totalGuests: 2,
    index: 102,
  },
  {
    name1: "Tim Caldwell",
    name2: "Kristin Caldwell",
    totalGuests: 2,
    index: 103,
  },
  {
    name1: "Tom Harrison",
    name2: "Becca Harrison",
    totalGuests: 3,
    index: 104,
  },
  {
    name1: "Wesley Bowers",
    name2: "Annette Bowers",
    totalGuests: 2,
    index: 105,
  },
  {
    name1: "William Bowers, III",
    name2: "Carol Bowers",
    totalGuests: 2,
    index: 106,
  },
  {
    name1: "William Erickson",
    name2: "Becky Erickson",
    totalGuests: 2,
    index: 107,
  },
  {
    name1: "William Jackson",
    name2: "Shelby Jackson",
    totalGuests: 2,
    index: 108,
  },
  {
    name1: "William T. Bowers",
    name2: "Patricia Bowers",
    totalGuests: 2,
    index: 109,
  },
  {
    name1: "William Yates",
    name2: "William Yates",
    totalGuests: 2,
    index: 110,
  },
  {
    name1: "Yaelie Mashburn",
    name2: "Yaelie Mashburn",
    totalGuests: 2,
    index: 111,
  },
  {
    name1: "Yudhister Bhatnager",
    name2: "Colleen Bhatnager",
    totalGuests: 2,
    index: 112,
  },
  {
    name1: "Yvonne Sporrer",
    name2: "Yvonne Sporrer",
    totalGuests: 2,
    index: 113,
  },
  {
    name1: "Catharine Magel",
    name2: "David  Kniepkamp",
    totalGuests: 2,
    index: 114,
  },

  {
    name1: "Yvonne Schwandt",
    name2: "Yvonne Schwandt",
    totalGuests: 2,
    index: 115,
  },

  {
    name1: "Sean Small",
    name2: "Sean Small",
    totalGuests: 2,
    index: 116,
  },

  {
    name1: "Cooper Schneider",
    name2: "Cooper Schneider",
    totalGuests: 1,
    index: 114,
  },

  {
    name1: "Brooke Pondof",
    name2: "Adam Ricks",
    totalGuests: 2,
    index: 115,
  },

  {
    name1: "Andrei Krozel",
    name2: "Andrei Krozel",
    totalGuests: 1,
    index: 116,
  },

  {
    name1: "Brandon Green",
    name2: "Brandon Green",
    totalGuests: 1,
    index: 117,
  },

  {
    name1: "Sam Zychinski",
    name2: "Sam Zychinski",
    totalGuests: 1,
    index: 118,
  },

  {
    name1: "JR Ditter",
    name2: "JR Ditter",
    totalGuests: 1,
    index: 119,
  },

  {
    name1: "Chris Vollrath",
    name2: "Chris Vollrath",
    totalGuests: 1,
    index: 120,
  },
  {
    name1: "Francis Lo",
    name2: "Francis Lo",
    totalGuests: 2,
    index: 121,
  },
];
